path = ../../../../3rdparty/SFML-2.5.1
monster_inheritance:
	g++ ./monster_inheritance.cpp -std=c++11 -o monster_inheritance.exe -I $(path)/include -L $(path)/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
