path = ../../../3rdparty/SFML-2.5.1

default: 1circle_wall 2circle_closest_point 3circle_circle 4circle_line 5circle_rectangle 6raycasting_circle_line

1circle_wall:
	g++ ./1circle_wall.cpp -std=c++17 -o 1circle_wall.exe -I $(path)/include -L $(path)/lib -lsfml-graphics -lsfml-window -lsfml-system 

2circle_closest_point:
	g++ ./2circle_closest_point.cpp -std=c++17 -o 2circle_closest_point.exe -I $(path)/include -L $(path)/lib -lsfml-graphics -lsfml-window -lsfml-system 


3circle_circle:
	g++ ./3circle_circle.cpp -std=c++17 -o 3circle_circle.exe -I $(path)/include -L $(path)/lib -lsfml-graphics -lsfml-window -lsfml-system 


4circle_line:
	g++ ./4circle_line.cpp -std=c++17 -o 4circle_line.exe -I $(path)/include -L $(path)/lib -lsfml-graphics -lsfml-window -lsfml-system 

5circle_rectangle:
	g++ ./5circle_rectangle.cpp -std=c++17 -o 5circle_rectangle.exe -I $(path)/include -L $(path)/lib -lsfml-graphics -lsfml-window -lsfml-system 

6raycasting_circle_line:
	g++ ./6raycasting_circle_line.cpp -std=c++17 -o 6raycasting_circle_line.exe -I $(path)/include -L $(path)/lib -lsfml-graphics -lsfml-window -lsfml-system 
